name: Run ChomeNS Bot

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

concurrency:
  group: chomens-bot
  cancel-in-progress: true

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 340

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Pull LFS
        run: |
          git lfs install
          git lfs pull

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin

      - name: Verify jar
        run: |
          test -f chomens.jar
          jar tf chomens.jar >/dev/null
          echo "Jar OK"

      - name: Create config
        run: |
          sed \
          -e "s|__DB_PASSWORD__|${{ secrets.DB_PASSWORD }}|g" \
          -e "s|__DISCORD_TOKEN__|${{ secrets.DISCORD_TOKEN }}|g" \
          config.example.yml > config.yml

      - name: Start replacement timer
        run: |
          (
            sleep 19800

            echo "5.5 hours reached"

            curl \
              -X POST \
              -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/run-bot.yml/dispatches \
              -d '{"ref":"main"}'

            echo "Replacement started"
            exit 0
          ) &

      - name: Run bot
        run: |
          set -e

          java -Xms6G -Xmx6G -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -jar chomens.jar

      - name: Restart after crash
        if: always()
        run: |
          echo "Restarting bot"

          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/run-bot.yml/dispatches \
            -d '{"ref":"main"}'
