name: Check ChomeNS Jar

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Check jar exists
        run: |
          ls -lh
          test -f chomens.jar

      - name: Validate jar
        run: |
          file chomens.jar
          jar tf chomens.jar > /dev/null
          echo "JAR is valid"
